
import os
import time
import base64
import json
import re
import requests
from pathlib import Path

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")  # Replace with your GitHub token 
HEADERS = {
    "Authorization": f"Bearer {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
}

SEARCH_QUERIES = [
    "language:csharp UnityEngine.InputSystem extension:cs",
    "language:csharp ISystem ComponentData extension:cs",
    "language:csharp IJobParallelFor BurstCompile extension:cs",
    "language:csharp Addressables.LoadAssetAsync extension:cs",
    "language:csharp UIDocument QueryExtensions extension:cs",
    "language:csharp Awaitable NextFrameAsync extension:cs",
    "language:csharp UniversalRenderPipeline RenderFeature extension:cs",
    "language:csharp Rigidbody linearVelocity extension:cs",
    "language:csharp NetworkBehaviour Netcode extension:cs",
    "language:csharp PhysicsWorld RaycastInput extension:cs",
    "language:csharp MonoBehaviour RequireComponent SerializeField extension:cs",
    "language:csharp ScriptableObject CreateAssetMenu extension:cs",
    "language:csharp RenderTexture CommandBuffer extension:cs",
]


def search_github(query: str, page: int = 1) -> dict:
    url = "https://api.github.com/search/code"
    params = {"q": query, "per_page": 30, "page": page}
    resp = requests.get(url, headers=HEADERS, params=params)

    remaining = int(resp.headers.get("X-RateLimit-Remaining", 1))
    if remaining < 3:
        reset_time = int(resp.headers.get("X-RateLimit-Reset", time.time() + 60))
        sleep_for = max(reset_time - time.time() + 2, 5)
        print(f"  Rate limit low — sleeping {sleep_for:.0f}s")
        time.sleep(sleep_for)

    if resp.status_code == 403:
        print("  Rate limited — sleeping 62s")
        time.sleep(62)
        return search_github(query, page)

    resp.raise_for_status()
    return resp.json()


def fetch_file_content(url: str) -> str | None:
    resp = requests.get(url, headers=HEADERS,timeout=20)
    if resp.status_code != 200:
        return None
    data = resp.json()
    if data.get("encoding") == "base64":
        return base64.b64decode(data["content"]).decode("utf-8", errors="ignore")
    return data.get("content")


def is_quality_script(code: str) -> bool:
    """To filter out stubs, generated files and non-Unity files."""
    if "using UnityEngine" not in code:
        return False
    if any(x in code for x in ["<auto-generated>", "This code was generated", "DO NOT EDIT"]):
        return False
    code_lines = [l for l in code.splitlines() if l.strip() and not l.strip().startswith("//")]
    if len(code_lines) < 20:
        return False
    if not re.search(r'\bclass\s+\w+', code):
        return False
    if any(x in code.lower() for x in ["[test]", "[testfixture]", "nunit", "unitytest"]):
        return False
    has_methods = len(re.findall(r'(void|bool|int|float|string|IEnumerator|Awaitable)\s+\w+\s*\(', code)) >= 2
    return has_methods


def detect_version_hints(code: str) -> dict:
    hints = {
        "has_new_input":      "InputSystem" in code or "InputAction" in code,
        "has_dots":           any(x in code for x in ["ISystem", "ComponentData", "EntityManager"]),
        "has_jobs":           "IJob" in code or "BurstCompile" in code,
        "has_addressables":   "Addressables" in code,
        "has_ui_toolkit":     "UIDocument" in code or "VisualElement" in code,
        "has_awaitable":      "Awaitable" in code,
        "has_linear_vel":     "linearVelocity" in code,
        "has_urp":            "UniversalRenderPipeline" in code,
        "has_old_input":      bool(re.search(r'\bInput\.Get(Key|Axis|Button)', code)),
        "has_old_ui":         "using UnityEngine.UI;" in code and "UIDocument" not in code,
        "has_coroutine":      "StartCoroutine" in code,
        "has_find":           "FindObjectOfType" in code or "FindGameObjectWithTag" in code,
        "has_camera_main":    "Camera.main" in code,
    }
    hints["modern_score"] = sum([hints["has_new_input"], hints["has_dots"], hints["has_jobs"],
                                  hints["has_addressables"], hints["has_ui_toolkit"],
                                  hints["has_awaitable"], hints["has_linear_vel"], hints["has_urp"]])
    hints["legacy_score"] = sum([hints["has_old_input"], hints["has_old_ui"],
                                  hints["has_coroutine"], hints["has_find"]])
    return hints


def scrape(output_dir: str = "./raw_scripts", max_per_query: int = 100):
    Path(output_dir).mkdir(exist_ok=True)
    seen_shas = set()
    total = 0

    for query in SEARCH_QUERIES:
        print(f"\nQuery: {query}")
        page, query_count = 1, 0

        while query_count < max_per_query:
            results = search_github(query, page)
            items = results.get("items", [])
            if not items:
                break

            for item in items:
                sha = item["sha"]
                if sha in seen_shas:
                    continue
                seen_shas.add(sha)

                time.sleep(0.5)
                code = fetch_file_content(item["url"])
                if not code or not is_quality_script(code):
                    continue

                hints = detect_version_hints(code)
                record = {
                    "sha": sha,
                    "filename": item["name"],
                    "repo": item["repository"]["full_name"],
                    "html_url": item["html_url"],
                    "code": code,
                    "hints": hints,
                }
                out_path = Path(output_dir) / f"{sha[:12]}_{item['name']}"
                out_path.write_text(json.dumps(record, indent=2))
                query_count += 1
                total += 1
                print(f"  [{total}] {item['name']}  modern={hints['modern_score']} legacy={hints['legacy_score']}")

            page += 1
            time.sleep(2)

    print(f"\nDone. Scraped {total} scripts → {output_dir}/")


if __name__ == "__main__":
    scrape(max_per_query=100)  